// search
export const UPDATE_SEARCHING = "UPDATE_SEARCHING";
export const SET_ENTERED = "SET_ENTERED";

// typePin
export const SET_TYPE_PIN_TITLE = "SET_TYPE_PIN_TITLE";

// pins
export const REFRESH_RECOMENDATION_PINS = "REFRESH_RECOMENDATION_PINS";
export const SET_RECOMENDATION_PINS = "SET_RECOMENDATION_PINS";
export const REFRESH_RECOMENDATION_HINTS = "REFRESH_RECOMENDATION_HINTS";
export const SET_RECOMENDATION_HINTS = "SET_RECOMENDATION_HINTS";
